### ISSUE TITLE
SQM values

### ISSUE THREAD

**Issue by porkyhttp** [romanhujer/SQM#1]
SQM values, has been compared with values of an official SQM device???

**Comment by romanhujer** [comment]
Yes, I compared  my prototypes with the origilnal Unihedron SQM.
After setting the default "SQM offset" the measurements show a +-0.1MAS  error
(SQM temperature calibration is need to turn off does not work properly)

**Comment by porkyhttp** [comment]
Which version of the BMx280I2C.h did you used?

**Comment by romanhujer** [comment]
The resulting machine code is smaller when using BMx280I2C.h than with BME280I2C.h in ATMega328p, there is no more space. Extended functions that are in BMx280I2C.h do not need here.

Roman

**Comment by porkyhttp** [comment]
This code with libs are to big to fit in an Arduino Nano or Uno. Is possible to have a version without the display support? I only need serial connection via USB and or via INDI
